version: '3.8'
name: "Transcription-Service"
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app/src
      - workspaceFolder=""
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --reload --reload-dir /app/src 